### PR TITLE
add trafik pecs to restaurants

### PR DESCRIPTION
**Pull request by peppertom**
https://imgur.com/a/Po9CQ

### CODE REVIEW

**Comment by wolfika** [comment]
Hi @peppertom! Thanks for the PR. Please make sure to tidy the output a little bit. We don't want to have "unnecessary" strings in the menu items output, like `Mai Napi xx.yy`, `...`, and `Továbbiak`. Otherwise, good job!

**Comment by ocReaper** [comment]
Hi @peppertom!
Don't forget to add this restaurant to the readme too! 😉

**Comment by ocReaper** [comment]
I've also added this restaurant in my PR, but I've used their site instead of facebook, which has a more stable structure

**Comment by wolfika** [comment]
Closing this as @ocReaper has implemented a more up-to-date version of the provider. Thanks a lot though!

**Pull request closed without merging**
